### ISSUE TITLE
Kernel panic and lack of bandwidth throughput.

### ISSUE THREAD

**Issue by ghost** [marywangran/Elastic-TCP#1]
Message from syslogd@localhost at Feb 27 11:11:22 ...
 kernel:[   11.424503] Kernel panic - not syncing: Fatal exception in interrupt

When I test this cc implement, will cause a Kernel panic and can't get full bandwidth throughput.

**Comment by marywangran** [comment]
plesae give details on panic.
RIP?STACK? ...

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13215166/109406865-6b3bf680-79b7-11eb-96cd-40708e893bf9.png)

I cannot reproduce the kernel panic right now, but the bandwidth problem still exists, I have a 30mbps VPS, the top one is PCC-vivace, the rest of the two is Elastic-TCP's result.

**Comment by marywangran** [comment]
try the latest version :-(

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13215166/109408221-384b3000-79c2-11eb-9fa3-565e2a41ce89.png)
I updated to commit [e6ebb05
](https://github.com/marywangran/Elastic-TCP/commit/e6ebb05dbcf80de3d669f007f42c728c6586dbb4), the problem still exists. The first one is BBR v2, the second one is PCC-vivace, the rest of the two is Elastic-TCP 's result.

**Comment by ghost** [comment]
https://github.com/marywangran/Elastic-TCP/blob/e6ebb05dbcf80de3d669f007f42c728c6586dbb4/tcp_elastic.c#L35

I think u forgot to div `cwnd` ![formula](https://render.githubusercontent.com/render/math?math=\frac{\WWF}{cwnd})

**Comment by ghost** [comment]
After adding the div cwnd, the bandwidth throughput issue got fixed.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13215166/109428073-3e77f580-7a30-11eb-9206-5b0830b3fb3f.png)
Elastic-TCP's result after fixed.
